# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
warnings_are_errors: false
cache: packages
R: bioc-release

bioc_required: true
bioc_packages:
  - flowCore

addons:
  apt:
     sources:
     - ubuntu-toolchain-r-test
     packages:
     - gcc-4.8
     - g++-4.8
